version: '3.9'

services:
  web:
    container_name: django-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - cache
  db:
    container_name: django-db
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data
  cache:
    container_name: django-redis
    image: redis:7.0.0-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}

# version: "3.9"
   
# services:
#   redis:
#     container_name: django-redis
#     image: redis
#     command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
#     ports:
#       - "14000:6379"
#     env_file:
#       - ./project/.env
#   db:
#     container_name: django-db
#     image: postgres:14.3-alpine
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     env_file:
#       - ./project/.env
#   web:
#     container_name: django-web
#     build: ./project
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     stdin_open: true
#     tty: true
#     env_file:
#       - ./project/.env