# Generated by Django 4.1.5 on 2023-01-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_tokenpolls_polls_pollrespondents_openquestions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closedanswers',
            options={'verbose_name': 'ClosedAnswers', 'verbose_name_plural': 'ClosedAnswers'},
        ),
        migrations.AlterModelOptions(
            name='closedquestions',
            options={'verbose_name': 'ClosedQuestions', 'verbose_name_plural': 'ClosedQuestions'},
        ),
        migrations.AlterModelOptions(
            name='openanswers',
            options={'verbose_name': 'OpenAnswers', 'verbose_name_plural': 'OpenAnswers'},
        ),
        migrations.AlterModelOptions(
            name='openquestions',
            options={'verbose_name': 'OpenQuestions', 'verbose_name_plural': 'OpenQuestions'},
        ),
        migrations.AlterModelOptions(
            name='pollrespondents',
            options={'verbose_name': 'PollRespondents', 'verbose_name_plural': 'PollRespondents'},
        ),
        migrations.AlterModelOptions(
            name='polls',
            options={'verbose_name': 'Polls', 'verbose_name_plural': 'Polls'},
        ),
        migrations.AlterModelOptions(
            name='tokenpolls',
            options={'verbose_name': 'TokenPolls', 'verbose_name_plural': 'TokenPolls'},
        ),
        migrations.AlterModelOptions(
            name='userpollstatus',
            options={'verbose_name': 'UserPollStatus', 'verbose_name_plural': 'UserPollStatus'},
        ),
        migrations.AddField(
            model_name='polls',
            name='poll_is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
