# Generated by Django 4.1.5 on 2023-01-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_closedanswers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closedanswers',
            options={'ordering': ['order'], 'verbose_name': 'ClosedAnswers', 'verbose_name_plural': 'ClosedAnswers'},
        ),
        migrations.AddField(
            model_name='closedanswers',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
