# Generated by Django 4.1.5 on 2023-01-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_closedanswers_options_closedanswers_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedanswers',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
