# Generated by Django 4.1.5 on 2023-01-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_closedanswers_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollrespondents',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpollstatus',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
