# Generated by Django 4.1.5 on 2023-01-25 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_pollrespondents_answered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='poll_end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 7, 34, 15, 125737, tzinfo=datetime.timezone.utc)),
        ),
    ]
