# Generated by Django 4.1.5 on 2023-01-25 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_polls_poll_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='poll_is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='polls',
            name='poll_end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 8, 53, 23, 537812, tzinfo=datetime.timezone.utc)),
        ),
    ]
