# Generated by Django 4.1.5 on 2023-01-25 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_polls_poll_is_published_alter_polls_poll_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenpolls',
            name='answers_hash',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polls',
            name='poll_end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 17, 3, 31, 366267, tzinfo=datetime.timezone.utc)),
        ),
    ]
