# Generated by Django 4.1.5 on 2023-01-25 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_tokenpolls_answers_hash_alter_polls_poll_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenpolls',
            name='poll_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='polls',
            name='poll_end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 18, 59, 6, 512875, tzinfo=datetime.timezone.utc)),
        ),
    ]
