# Generated by Django 4.1.5 on 2023-01-25 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_tokenpolls_poll_ended_alter_polls_poll_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='poll_conclusion',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='poll_end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 20, 5, 39, 340118, tzinfo=datetime.timezone.utc)),
        ),
    ]
